### ISSUE TITLE
[Android] 1.19 Android Feedback (bugreports and feature requests)

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [wesnoth/wesnoth#10326]
### Describe the desired feature

- [ ] bugreport: major UX problem - the camera constantly drifts either right or down for me, making it nearly-unplayable

steps to reproduce:

to get right drift - click on the top-right map to move camera 
downward drift - drag camera with mouse on the map directly

- [x] feature request: ways of built-in access to the data folder, since Android/data is often very difficult or impossible to access on newer versions of android. This is needed for modders to test their unpublished add-ons on mobile, and for players to be able to move their data/save files/etc. from desktop to mobile (#10389)

- [x] feature request: allowing units to move/attack by tapping on the unit then tapping on a target tile/enemy in range (somewhat similarly to how 1.14 port allowed it via click emulation), insted of only being able to drag. This doesn't have to be on by default, it can be a toggleable option, but it would be a lot more convenient than dragging in my opinion.

this can also be paired other controls-related options like "hold to rightclick instead of double-tapping to rightclick" option in mobile settings, to add more customization for controls, and a two-finger drag for camera movement instead of single-finger

- [ ] UX bugreport - the "Menu" menu in the top-left closes when scrolling down. making it really annoying to try to reach the "quit to desktop" option

- **Version: 1.19.13**
- **OS: Android**

**Comment by rodolphecombe** [comment]
The auto-scrolling-map issue only happens from the start of enemy turn on my phone and can be stopped by clicking anywhere on the mini-map

**Comment by ForestDragon-wesnoth** [comment]
> The auto-scrolling-map issue only happens from the start of enemy turn on my phone and can be stopped by clicking anywhere on the mini-map

Interesting. on my tablet clicking on the minimap triggers horizontal auto-scroll bug instead

**Comment by soliton-** [comment]
>  feature request: ways of built-in access to the data folder, since Android/data is often very difficult or impossible to access on newer versions of android. This is needed for modders to test their unpublished add-ons on mobile, and for players to be able to move their data/save files/etc. from desktop to mobile

Instead of putting work into custom access to a problematic dir might as well put the data in an easier to acces dir in the first place.

**Comment by ForestDragon-wesnoth** [comment]
> > feature request: ways of built-in access to the data folder, since Android/data is often very difficult or impossible to access on newer versions of android. This is needed for modders to test their unpublished add-ons on mobile, and for players to be able to move their data/save files/etc. from desktop to mobile
> 
> Instead of putting work into custom access to a problematic dir might as well put the data in an easier to acces dir in the first place.

Yeah, that sounds like the best approach. Maybe giving the wesnoth app more file permissions, but putting the wesnoth data folder at main storage level (where Downloads/Pictures/Music/etc. folders are located), especially considering that the wesnoth folder is located in pretty easy-to-access places on other operating systems.

**Comment by babaissarkar** [comment]
> > feature request: ways of built-in access to the data folder, since Android/data is often very difficult or impossible to access on newer versions of android. This is needed for modders to test their unpublished add-ons on mobile, and for players to be able to move their data/save files/etc. from desktop to mobile
> 
> Instead of putting work into custom access to a problematic dir might as well put the data in an easier to acces dir in the first place.

`Android/data` is the easiest to access programmatically and recommended for App Data unless you need something very specific. Latest Android versions would require the user to choose a folder at least once before Wesnoth can use that. (Android SAF restrictions)

**Comment by ForestDragon-wesnoth** [comment]
We can keep Android/Data the default data folder but which can be optionally moved to a more user-accessible location with the "Latest Android versions would require the user to choose a folder at least once before Wesnoth can use that." idea mentioned by babaissarkar

**Comment by babaissarkar** [comment]
> idea mentioned by babaissarkar

Android restriction rather than idea. 😓

**Comment by TheFlamelet** [comment]
I didnt know we had an android version beyond 1.14

**Comment by babaissarkar** [comment]
> I didnt know we had an android version beyond 1.14

Recently released on just sourceforge, alpha. Mentioned in 1.19.13 announcements on Discord

**Comment by babaissarkar** [comment]
@ForestDragon-wesnoth On latest master it is now possible to move unit by clicking on it then double tapping on target hex. I cannot make it single click because we lose hover info. (Wesnoth is extremely hover/tooltip heavy.)

**Comment by rodolphecombe** [comment]
> On latest master it is now possible to move unit by clicking on it then double tapping on target hex. I cannot make it single click because we lose hover info. (Wesnoth is extremely hover/tooltip heavy.)

Does clicking on the unit then single-clicking on a hex displays the hover info of said hex for the unit (defense) as discussed?

**Comment by babaissarkar** [comment]
> > On latest master it is now possible to move unit by clicking on it then double tapping on target hex. I cannot make it single click because we lose hover info. (Wesnoth is extremely hover/tooltip heavy.)
> 
> Does clicking on the unit then single-clicking on a hex displays the hover info of said hex for the unit (defense) as discussed?

Yes.

**Comment by babaissarkar** [comment]
@ForestDragon-wesnoth ^ ab07e81 adds at least one way to edit Addon file (I plan to do more work on this later).
Open any File dialog (Load Game/Map Editor -> Open File/Scenario Editor -> Addons Menu -> Open Addon Folder) > Navigate to the file you want to edit > Tap "Open External" > Select a Text Editor (or anything you need) app from the list.

**Comment by babaissarkar** [comment]
Progress update: #10389 (User data folder import/export) done

**Comment by babaissarkar** [comment]
- [ ] BUG: coming back into Wesnoth from another Activity (app) causes it to crash. Will be investigated. Possibly weird interaction between Java (Android) -> C++ -> SDL
- [x] FR: Back button does not work. It should perform equivalent action as Esc on PC.
- [x] FR: Unlike PC, no way to skip messages in game, since no Esc key. A skip button like the story screen could be nice here. (dialog heavy android games do this)

**Comment by soliton-** [comment]
> FR: Unlike PC, no way to skip messages in game, since no Esc key. A skip button like the story screen could be nice here. (dialog heavy android games do this)

The idea to have the back action consistently work like ESC seems quite good to me. If we can unintrusively add a skip button here that's cool too but seems not really needed then.

**Comment by AdityaMH** [comment]
Add UI scale for android because ui too small.
Can hurt everyone eyes just because to see unit hp bar or flag.

**Comment by babaissarkar** [comment]
> Add UI scale for android because ui too small. Can hurt everyone eyes just because to see unit hp bar or flag.

Known but complex issue, we are working on it.

**Comment by Refumee** [comment]
Hello :)

Here is the second Issue with not able to use the sliders:
https://forums.wesnoth.org/viewtopic.php?p=699796#p699796
I also represented the issue. I think it has something todo with "Pixel scale multiplier".

I also recognised that, if I pick a unit the game locks me on that said unit. How can I get loose of that unit? I would like to check out enemy units.

Also if I wanna check out enemy units, I hover or click on them. Funnily enough, if I do that and said unit moved already, I can't see how much that unit can move. Sure I can check all moves of all enemies at once, but I wanna check out singular units.

This one isnt really a issue, but in TDG we got a "New Recruits" Window, the Units themselves arent in the right spot @Dalas121 . I dont see any chance to fix that.

**Comment by babaissarkar** [comment]
> I also recognised that, if I pick a unit the game locks me on that said unit. How can I get loose of that unit? I would like to check out enemy units.
> 
> Also if I wanna check out enemy units, I hover or click on them. Funnily enough, if I do that and said unit moved already, I can't see how much that unit can move. Sure I can check all moves of all enemies at once, but I wanna check out singular units.

Can you create a separate issue on this? I noticed this too.

Also, anything related to pixel scale will need to wait until SDL3 is merged. (Sorry) Ref: @Vultraz .

**Comment by AdityaMH** [comment]
> Known but complex issue, we are working on it.

Why not to take a look unciv or commander wars?

**Comment by licaon-kter** [comment]
1.19.16 F-Droid or Sourceforge arm64 APK crash
```
...
D Unpack  : Unpacking Core Data:26042/26043
D Unpack  : Unpacking Core Data:26043/26043
D Unpack  : Done unpacking Core Data
D InitActivity: Starting to download music.zip from https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.19.16/android-data/music.zip/download
D Download: URL: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.19.16/android-data/music.zip/download
D Download: Download success from URL: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.19.16/android-data/music.zip/download
D InitActivity: Start unpack music.zip
D Unpack  : Start
D Unpack  : Unpacking Music:1/43
...
D Unpack  : Unpacking Music:42/43
D Unpack  : Unpacking Music:43/43
D Unpack  : Done unpacking Music
D InitActivity: Starting to download patch.zip from https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.19.16/android-data/patch.zip/download
D Download: URL: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.19.16/android-data/patch.zip/download
E Download: Server returned response: 404
D InitActivity: Stop unpack
D InitActivity: Launch wesnoth
V SDL     : Device: ...
V SDL     : Model: ...
V SDL     : onCreate()
D nativeloader: Load /data/app/~~dV1oyqY16Vb-W5LUiPceqA==/org.wesnoth.Wesnoth-mTnsx-f1af-FF6D3kQ8sbw==/base.apk!/lib/arm64-v8a/libSDL2.so using ns clns-4 from class loader (caller=<unknown>): ok
W SDL     : Request to get environment variables before JNI is ready
D nativeloader: Load /data/app/~~dV1oyqY16Vb-W5LUiPceqA==/org.wesnoth.Wesnoth-mTnsx-f1af-FF6D3kQ8sbw==/base.apk!/lib/arm64-v8a/libmain.so using ns clns-4 from class loader (caller=<unknown>): ok
V SDL     : nativeSetupJNI()
V SDL     : AUDIO nativeSetupJNI()
V SDL     : CONTROLLER nativeSetupJNI()
W Sensors : Cannot get virtualdevice_native service
V SDL     : onStart()
V SDL     : onResume()
V SDL     : surfaceCreated()
V SDL     : surfaceChanged()
V SDL     : Window size: 2340x1003
V SDL     : Device size: 2340x1080
V SDL     : Running main function SDL_main from library /data/app/~~dV1oyqY16Vb-W5LUiPceqA==/org.wesnoth.Wesnoth-mTnsx-f1af-FF6D3kQ8sbw==/lib/arm64/libmain.so
V SDL     : nativeRunMain()
I wesnoth : Battle for Wesnoth v1.19.16+dev arm
I wesnoth : Started on Fri Sep 26 ---  2025
I wesnoth : 
I wesnoth : Could not find game data directory ''
---crash
F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7116cd41a8)
F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4218 (RenderThread), pid 4199 (SDLActivity)
E cutils-trace: Error opening trace file: No such file or directory (2)
E DEBUG   : failed to readlink /proc/4218/fd/70: No such file or directory
E DEBUG   : failed to readlink /proc/4218/fd/71: No such file or directory
E DEBUG   : failed to readlink /proc/4218/fd/72: No such file or directory
E DEBUG   : failed to readlink /proc/4218/fd/73: No such file or directory
E DEBUG   : failed to readlink /proc/4218/fd/74: No such file or directory
I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x726429d678)
F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x726429d678)
I crash_dump64: performing dump of process 4199 (target tid = 4218)
```

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/689ca3a5076e111b9afd83fa4c3e869f1c0edad7

**Comment by soliton-** [comment]
Looks like the android version is built with `WESNOTH_PATH` set so that is being used and is surely not pointing to a valid game data dir.

Either it should be built with the right WESNOTH_PATH set (not sure that's possible for all supported android versions) or not set at all.

**Comment by babaissarkar** [comment]
> 1.19.16 F-Droid or Sourceforge arm64 APK crash
> 

https://github.com/wesnoth/wesnoth/pull/10585 should fix it. (Unsets `WESNOTH_PATH` for Android)

**Comment by soliton-** [comment]
Btw, it should not be a crash. We're calling `exit(1)` so it should be a "normal" termination? Sounds like the java code around wesnoth does not like that?

**Comment by licaon-kter** [comment]
The app exits all of the sudden.

Yes, I agree it's not a crash, but to the rest of the users... it's a crash. :)

**Comment by soliton-** [comment]
Right, but I mean
> F libc    : FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7116cd41a8)
F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4218 (RenderThread), pid 4199 (SDLActivity)

looks like it is actually crashing.

**Comment by babaissarkar** [comment]
@licaon-kter a4c4c4fa6dda359f2d7210677afdceabecce5d22 (#10585) should fix that issue. Is there any other way to push a hotfix to fdroid other than a tag?

**Comment by licaon-kter** [comment]
We can buili from any commit, but we need a higher versionCode.

**Comment by babaissarkar** [comment]
> We can buili from any commit, but we need a higher versionCode.

@licaon-kter 
A new tag was pushed (1.19.16.1), so that'd trigger a new build, right? (Version code is still same, does that require change?)

**Comment by FrenchPrick** [comment]
Anyway to change the display in the app, I tried to mess with the preference file, but nothing happens.

<img width="1600" height="720" alt="Image" src="https://github.com/user-attachments/assets/2cceab53-d67e-47d7-b056-c8d4c3e5dc07" />

**Comment by licaon-kter** [comment]
@babaissarkar yes. Like I said, we need a higher versionCode :)

**Comment by babaissarkar** [comment]
> [@babaissarkar](https://github.com/babaissarkar) yes. Like I said, we need a higher versionCode :)

@licaon-kter will this be enough for incrementing the versionCode? or something else is needed? (in `app/build.gradle`)
```diff
     // Use custom APK versionCode for each ABI
     def abiCodes = ['armeabi-v7a': 1, 'arm64-v8a': 2, 'x86': 3, 'x86_64': 4]
     applicationVariants.all { variant ->
         variant.outputs.each { output ->
+            def patchCode = 1
             def abiCode = abiCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0)
-            output.versionCodeOverride = defaultConfig.versionCode * 1000 + abiCode
+            output.versionCodeOverride = defaultConfig.versionCode * 1000 + patchCode * 100 + abiCode
         }
     }
```

**Comment by licaon-kter** [comment]
@babaissarkar not a dev, on a first look, we use versionCode and match your calculation, https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.wesnoth.Wesnoth.yml#L177-L179 but... we can't use patchCode as checkupdate does not run code.

So... I guess this is not a solution.

Why is there an issue to tag a minor release with a proper versionCode?

**Comment by babaissarkar** [comment]
> [@babaissarkar](https://github.com/babaissarkar) not a dev, on a first look, we use versionCode and match your calculation, https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.wesnoth.Wesnoth.yml#L177-L179 but... we can't use patchCode as checkupdate does not run code.
> 
> So... I guess this is not a solution.
> 
> Why is there an issue to tag a minor release with a proper versionCode?

@licaon-kter just curious. Anyway, I've incremented the main version code: https://github.com/wesnoth/wesnoth/tree/1.19.16.1, hopefully this works.

**Comment by licaon-kter** [comment]
@babaissarkar hmm? https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11528618244#L12845

**Comment by babaissarkar** [comment]
> [@babaissarkar](https://github.com/babaissarkar) hmm? https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11528618244#L12845

https://github.com/wesnoth/wesnoth/commit/974697748efe3e8a4ab1570f173c06023ddf24f2 should fix that. (versionCode was too long)

**Comment by FrenchPrick** [comment]
> Anyway to change the display in the app, I tried to mess with the preference file, but nothing happens.
> <img alt="Image" width="1600" height="720" src="https://private-user-images.githubusercontent.com/75982685/494733092-2cceab53-d67e-47d7-b056-c8d4c3e5dc07.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkxMzU2OTIsIm5iZiI6MTc1OTEzNTM5MiwicGF0aCI6Ii83NTk4MjY4NS80OTQ3MzMwOTItMmNjZWFiNTMtZDY3ZS00N2Q3LWIwNTYtYzhkNGMzZTVkYzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI5VDA4NDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZDhhZjlkMjdjMGYyMWMzZTQxYTI1NTE0OGY0NzQ3YmI2Njc3MGIyZjk5MTNiMTM2NTZlZDQ2ZjQxODA4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J_uuxbFeu9EnAkonuIkG-l5zGUQbaMqUgR_7zbPuz_U">

So is there no solution for this? Or am I just dumb?

**Comment by licaon-kter** [comment]
@babaissarkar thanks

**Comment by soliton-** [comment]
> So is there no solution for this? Or am I just dumb?

You provided no context. What version is this? Is that on android? If you built a random git version then build again.

**Comment by FrenchPrick** [comment]
> > So is there no solution for this? Or am I just dumb?
> 
> You provided no context. What version is this? Is that on android? If you built a random git version then build again.

Yes, it on Android I got it from Actions specifically Android CI #1008 by Babaissarkar.

https://github.com/wesnoth/wesnoth/actions/runs/18054165695

**Comment by soliton-** [comment]
Get a newer one then.

**Comment by FrenchPrick** [comment]
> Get a newer one then.

Thanks man, and sorry for wasting your time.

**Comment by babaissarkar** [comment]
@FrenchPrick that display issue is most likely solved in the latest master build.

**Comment by FrenchPrick** [comment]
> [@FrenchPrick](https://github.com/FrenchPrick) that display issue is most likely solved in the latest master build.

Yeah, it did, I was just hesitate on updating my app without knowing if the issue was solved, cause am on a limited data plan.

**Comment by oldlaptop** [comment]
> > Add UI scale for android because ui too small. Can hurt everyone eyes just because to see unit hp bar or flag.
> 
> Known but complex issue, we are working on it.

Is this tracked separately anywhere, and is it anything you're interested in patches for?

**Comment by babaissarkar** [comment]
> > > Add UI scale for android because ui too small. Can hurt everyone eyes just because to see unit hp bar or flag.
> > 
> > 
> > Known but complex issue, we are working on it.
> 
> Is this tracked separately anywhere, and is it anything you're interested in patches for?

Currently waiting for SDL 3.4, and its not separately tracked. @Vultraz for more info.

**Comment by Tyruxanj** [comment]
> * [ ]  bugreport: major UX problem - the camera constantly drifts either right or down for me, making it nearly-unplayable
> 
> steps to reproduce:
> 
> to get right drift - click on the top-right map to move camera downward drift - drag camera with mouse on the map directly

I am on version 1.19.6+dev (latest fdroid build) using Galaxy Tab S7 FE and this issue persists for a couple months now. I believe the reason is that the game is adapted with phones with smaller screens in mind since the top left portion of the game works properly and your touch anywhere else gets mapped in a way to fit the working left portion, only to then remap to your original touch whilst moving units, ultimately messing your gameplay. If you touch anywhere outside said safe area or the minimap which is at the right, camera starts drifting like its running in the 90s. This issue is only in game and I haven't seen it happen in main menu. Lmk if you need any testing from me.

**Comment by soliton-** [comment]
Some kind of scaling applied is not the same as the view constantly scrolling in some direction. Though it's a bit hard to tell from the original description if really constant scrolling is meant or just unexpected behavior when scrolling manually which could be the same scaling issue.

A scaling of x2 was reported as well for a phone with native resolution of 1224x2770 where wesnoth got a resolution of 1350x612 (see Preferences -> Display). So far I don't think anyone knows where the scaling comes from.

The game is definitely not adapted much for phones/tablets of any resolution so far. I imagine either the SDL wrapper we use or Android itself does enable some automatic scaling on some devices. My device has a native resolution of 2424x1080 and that is what wesnoth gets as well. Maybe it's some automatic for higher resolutions or some Android vendor adjustments. I don't know if the mentioned phone above is also from Samsung.

**Comment by tikend** [comment]
When using BT mouse and keyboard, the cursor position and hexagon selection are not in sync. So basically mouse is unusable.

**Comment by zef126** [comment]
I have the same problem as the opener of this issue and I think a shortcut like some small buttons after a long click above the unit can be a good shortcut to attack, recruit and call back units.
On all devices (computers with tactile screens included), the click from a keyboard must be differentiated from a click on the screen and don't provoke the same behaviour. The solution may be a mode to switch from keyboard to screen touching.

**Comment by soliton-** [comment]
> On all devices (computers with tactile screens included), the click from a keyboard must be differentiated from a click on the screen and don't provoke the same behaviour.

How would that be good? Then devices with a touch screen and no mouse/keyboard can never be usable?

**Comment by zef126** [comment]
I was simply thinking of differentiating between keyboard, mouse and touchscreen so that all actions in the game are possible from both, but that each is intuitive and easy to use and that it is not unplayable on the touchscreen. I don't know if this is feasible.

**Comment by Allespro** [comment]
SDL error android 8.1.0 lineageOS 15.1 https://github.com/libsdl-org/SDL/issues/13977

**Comment by soliton-** [comment]
Are you saying you compiled the app yourself with SDL3 and got that error? Sounds like the build was not done correctly then.

If you mean you got a SDL Error with our app then post the actual error message.

**Comment by Allespro** [comment]
> Are you saying you compiled the app yourself with SDL3 and got that error? Sounds like the build was not done correctly then.
> 
> If you mean you got a SDL Error with our app then post the actual error message.

no I get it from f-droid, latest 1.19.18

cannot locate symbol iconv_open like in mentioned issue

**Comment by soliton-** [comment]
I have no idea how the mentioned issue (closed as not actually an issue) is in any way related. Post the actual error message you get and if it somehow involves SDL3 then explain how that can be.

**Comment by Allespro** [comment]
> I have no idea how the mentioned issue (closed as not actually an issue) is in any way related. Post the actual error message you get and if it somehow involves SDL3 then explain how that can be.

can you please send how to build apk. ill try to fix myself

**Comment by soliton-** [comment]
Our CI builds an APK for each commit here: https://github.com/wesnoth/wesnoth/blob/master/.github/workflows/android.yml

F-Droid builds wesnoth here: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.wesnoth.Wesnoth.yml

**Comment by whynot2test** [comment]
Any updates regarding "camera drifting bug"? Maybe some workarounds ?

**Comment by babaissarkar** [comment]
> Any updates regarding "camera drifting bug"? Maybe some workarounds ?

No, sorry. It is hard to pin down.

**Comment by soliton-** [comment]
It would be good to get more details on that bug. Maybe there is some connection between device manufacturer or android version or something. So far I think it simply does not happen on a dev owned device. I've not yet seen it on a pixel 9a anyway.

**Comment by babaissarkar** [comment]
> It would be good to get more details on that bug.

@ForestDragon-wesnoth do you have any new findings? Would be good if can be consolidated here.

**Comment by rodolphecombe** [comment]
On small-screen devices, opening the preferences makes the game crash. If done during a scenario, the following message is shown before the crash. 

<img width="960" height="480" alt="Image" src="https://github.com/user-attachments/assets/90fe4b25-68d0-4a72-8a73-2ff14cd7b491" />

**Comment by Tepiggo** [comment]
@soliton-  
Dunno if its any help, but Ive been having this issue on the motorola g stylus 2025. I can get the scroll to stop if i **QUICKLY** tap on a tile while the screen is scrolling, however it will immediately begin to scroll again if i tap the screen and hold it just the tiniest bit too long. If i go to actions then select the next unit button, the screen will also play nice until i tap and drag to move said unit. (or tap too slowly).

 Another (perhaps related?) note is that if i am zoomed out to a point where the map does not move, when tapping and dragging to move a unit, the screen displays the unit going a completely different path from where im sending it (very common, maybe 100% of the time), however when i release my stylus, the unit goes to the tile my stylus is over every time.

**Comment by whynot2test** [comment]
> It would be good to get more details on that bug. 

Android 12 (emui 14) Huawei P50

**Comment by dks** [comment]
> > Any updates regarding "camera drifting bug"? Maybe some workarounds ?
> 
> No, sorry. It is hard to pin down.

I have same "camera drifting bug" on Honor Pad 10. So far I was able to figure out that the problem goes away if I turn off x2 scaling. Looks like real position of touch at the screen is not considering scaling, so if you click or try to do something at the bottom / right half of the screen it immediately starts to scroll there endlessly (as if you move mouse to the screen edge). 

However without scaling picture is to small. And I actually can't turn back x1 scaling. Sliders at the preferences menus unresponsive to touchscreen slide moves. I can click toggle buttons, but can not slide controls.

**Comment by whynot2test** [comment]
> > Any updates regarding "camera drifting bug"? Maybe some workarounds ?
> 
> No, sorry. It is hard to pin down.

I found the issue "roots", so:

Android system of my phone have 2 resolution Mods:
Low 1800x816
High 2700x1224
It is not in game resolution! but phone.


In game resolution with Low; 1290x612 NO BUG! But worse quality.

But with High settings, then in-game resolution 1720x816  I have this "scrolling bug"


![Image](https://github.com/user-attachments/assets/b28071bd-6aeb-4f44-a82c-88253ba79721)
![Image](https://github.com/user-attachments/assets/747ca0f5-df76-45c2-82d2-be32754b037d)
![Image](https://github.com/user-attachments/assets/cd40427e-3edc-4fdb-8443-71cf6fe73f87)
![Image](https://github.com/user-attachments/assets/5c4bab4d-0ec0-4ee5-8d97-fcecabfb3cdb)

with both Low and High I can not unclick fullscreen button as well as I can bot change pixel scale multiplier, it always 1 !?

I think the issue might be with "resolution re-calculation/adoption"

**Comment by Tepiggo** [comment]
Uhh found another bug, when selecting the celes instead of parchment for the theme, in preferences, the game crashes. It then proceeds to crash every time the app looks for "installed add ons" on app boot. Restarting phone does not fix.

**Comment by soliton-** [comment]
> Uhh found another bug, when selecting the celes instead of parchment for the theme, in preferences, the game crashes. It then proceeds to crash every time the app looks for "installed add ons" on app boot. Restarting phone does not fix.

Can't reproduce that. Do you get any kind of error message?

The theme likely errors out when showing the main menu so to fix that you'd need to edit the preferences file to set `gui2_theme` back to `default`.

**Comment by Tepiggo** [comment]
If im being honest with ya, i just deleted and reinstalled the app to fix it as i only beat the first two tutorial campaign levels. I am willing to try to break it again if it would be of help, but Im kinda hard locked out of the app when I do.  Like after I click to start, and the app begins to load, i would see that text on the loading screen beneath the bar before the app closes itself. :/

**Comment by Tepiggo** [comment]
Actually, by any chance is there a way to retrieve logs from a crashed session?

**Comment by rodolphecombe** [comment]
I have not succeeded on Android

**Comment by soliton-** [comment]
The logs are under the [Android/data](https://www.reddit.com/r/Android/comments/1875mar/solution_to_access_androiddata_subfolders_in/?tl=de) dir which depending on Android version can be difficult to access. If you can get there it's under `org.wesnoth.Wesnoth/files/logs`.

It's not clear whether you'll see anything in there though. Another option is to try https://f-droid.org/de/packages/com.f0x1d.logfox/ to record android logs.

**Comment by czarkoff** [comment]
On a foldable (OPPO Find N3) the game correctly identifies the landscape mode in both folded and unfolded states. The problem is that landscape mode is awkward to use in the unfolded state. It would be great if the game could identify the current orientation and rotate according to it. As this is probably only useful on foldables, this should probably be a setting in preferences, potentially with "Landscape", "Portrait" and "Auto" options.

**Comment by agasthene** [comment]
Dans la suite des problèmes avec Android,  cherchant un jeu sur f-droid j'ai choisi celui-ci un peu par hasard,  une fois ouvert et le téléchargement des données restantes, je me retrouve avec un jeu prévu pour pc et non mobile, il suffit de voir dans les options 

Mais, vu la taille d'écriture,  c'est impossible a jouer sur mon SM-G736B.  

Malgré la petite écriture,  j'essaie de changer certaine options comme la taille de l'écran.  Impossible. 

Le jeu n'est pas écrit non plus en langage neutre pour que cela soit la langue de l'os qui soit pris en compte.

Concernant les cannaux de communication,  il est nécessaire d'ajouter une adresse mail de contact, tout ne peut ce faire par le forum ou gîtes.

Pzr contre ce qui est étonnant c'est que le site web ne parle nullement de cette version Android.

**Comment by babaissarkar** [comment]
Posters can open separate issues now, we can use subissues feature of github to link them here. This issue is becoming too crowded.

**Comment by babaissarkar** [comment]
The resolution issue is known. Please don't report it multiple times.

**Comment by babaissarkar** [comment]
> On a foldable (OPPO Find N3) the game correctly identifies the landscape mode in both folded and unfolded states. The problem is that landscape mode is awkward to use in the unfolded state. It would be great if the game could identify the current orientation and rotate according to it. As this is probably only useful on foldables, this should probably be a setting in preferences, potentially with "Landscape", "Portrait" and "Auto" options.

@czarkoff Please open a new issue on this.

**Comment by rodolphecombe** [comment]
@agasthene 
Concernant la taille de police et la résolution, c'est en cours. Il fallait attendre la migration du jeu vers la version 3 du moteur graphique SDL, qui est utilisé pour le jeu, si j'ai bien compris. 
Normalement si, le jeu détecte automatiquement le langage du téléphone et le choisit. 
Il s'agit d'une version de développement. La version Android sera annoncée sur le site quand la version officielle sera publiée.

**Comment by agasthene** [comment]
@rodolphecombe ok. cependant il faudrait peut-être désactiver la version sur fdroid ou mettre une note a a ce sujet sur la boutique frdoid
quand cette version 3 est-elle prévue?

**Comment by rodolphecombe** [comment]
Pourquoi faudrait-il désactiver la version sur F-Droid ?
C'est un alpha (c'est littéralement la deuxième ligne de la description de l'application sur F-Droid). Le bug c'est justement que les gens puissent tester pour rapporter les bugs.
De mémoire la version officielle est prévue vers novembre mais je ne crois pas qu'il y ait eu d'annonce officielle nulle part.

**Comment by agasthene** [comment]
dans un premier temps il faudrait déverrouiller  la résolution.
Le changement de la taille des caractères ne doit pas influencer les menus elle devrait garder la mêmehauteur.  cependant le contenu deviendra défilent. 
pour ce qui ce trouve au dessus de l'écran: point de vie et autre. en l'état actuel il faudrait que le menu soit plus grand. 
il faudrait laisser un espace  a chaque extrémité de l'écran. nos écrans sous Android n'ont pas d'angle sec a 90⁰.

supprimer du menu les raccourcis 

a défaut de pouvoir changer la résolution, utiliser le zoom et dezoom avec les doigts

**Comment by babaissarkar** [comment]
> dans un premier temps il faudrait déverrouiller la résolution.

Wesnoth's backend, SDL, no longer seems to be supplying resolution list, so I doubt that's doable. There's an issue on resolution: #10918 

The rest seems reasonable, but opening separate issue will get it done faster and helps us with tracking.

@rodolphecombe please translate, I'm relying on translation tools here.

**Comment by rodolphecombe** [comment]
Je traduit comme demandé par babaissarkar : 
"Le backend de Wesnoth, SDL, semble ne plus fournir de liste de résolution [NdT : suite au passage de SDL2 à SDL3], donc je doute que ce soit faisable. Il y a déjà une issue ouverte à propos de la résolution : #10918 
Le reste semble raisonnable, mais ouvrir une issue séparée le verra résolu plus rapidement et nous aide à suivre ce qui reste à faire."

@babaissarkar It does not look like we are allowed to create sub-issues. I will add them as issues and you will have to link them as sub-issues of this one.

**Comment by babaissarkar** [comment]
> [@babaissarkar](https://github.com/babaissarkar) It does not look like we are allowed to create sub-issues. I will add them as issues and you will have to link them as sub-issues of this one.

@rodolphecombe That's fine. We'll link them, just open issues and mention this issue. I've already created two.

**Comment by agasthene** [comment]
> Je traduit comme demandé par babaissarkar: "Le backend de Wesnoth, SDL, semble ne plus de profiler de liste de résolution de [NdT : suite au passage de SDL2 à SDL3], donc je doute que ce situable. Il y a déjà une question ouverte à proposition de la résolution : [#10918](https://github.com/wesnoth/wesnoth/issues/10918) Le reste semble, mais open rêve une issue séparée le vera le rapide et nous aide à suivre ce qui reste à faire. »
> 
> [@babaissarkar](https://github.com/babaissarkar) Il ne semble pas que nous soyons autorisés à créer des sous-problèmes. Je les ajouterai comme questions et vous devrez les relier en tant que sous-numéros de celui-ci.

Personnellement si j'écris en français par facilité, parce que c'est ma langue maternelle et que j'ai écrit ma réponse précédente via mon téléphone, je peut aussi utiliser des outils de traduction pour lire les réponses en anglais.

l'option zoom dépendra si il y a changement de résolution. si la taille du jeux devient correcte pour le téléphone, il ne sera ps nécessaire d'utiliser le zoom.

**Comment by babaissarkar** [comment]
A solution for `bugreport: major UX problem - the camera constantly drifts either right or down for me, making it nearly-unplayable` is merged to master in #11581. Needs testing, but original author @ForestDragon-wesnoth mentioned this as solved for him at least. Players facing the same issue are requested to check if the issue is resolved or not during next Wesnoth Android release on FDroid (1.19.28).

**Comment by Steji** [comment]
If anyone still finds this an issue I've been playing fine for months by not using that zoom feature and using the in level zoom (long press -> zoom in) which works absolutely fine
