### ISSUE TITLE
A way to see "white names" in the lobby while observing (GNA #8871)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1102]
**[Original submission](https://gna.org/bugs/index.php?8871)** by anonymous on 2007-04-07

Item Groups: Networking and Multiplayer.

While observing, we can get the lobby joins, but there is no way to know when a game ends and someone who was playing is returned to the lobby.

I have three possible suggestions:

1) Also show these as lobby joins for observers, maybe with a "XXX has returned to the lobby" message instead. Maybe too much traffic and gets annoying to read? So see suggestion number 3.

2) A :getnames command for observers (and why not players) in a game on the server. This should query the server about the "white names", and show the server's response in the querying player's chat as "<server> Jackson jb JJ JohnDoe ...". (It would be nice to have the server sort the list it sends alphabetically.)

3) With the friends-list in 1.3, a modified version of 1. The server sends you (as an observer) all the "has returned to the lobby" messages, but your client only shows those of your friends. This could be the user-friendliest way to do this.

(Reproduced on all)
Release: 1.3-svn
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by jostephd** [comment]
> there is no way to know when a game ends and someone who was playing is returned to the lobby.

Nowadays, when a player leaves the game the other players/observers get notified. So this is fixed.

**Comment by soliton-** [comment]
They are talking about notifications while observing a game not while in the lobby. The request is for a notification/message when a player/friend joins the lobby after leaving a game.

**Comment by jostephd** [comment]
I thought the request was to be notified, during linger mode, of when other players left the match and returned to the lobby.

**Comment by jostephd** [comment]
Is this addressed by 661048d4a92419129d1d58571f3d218819c034eb / f137de499b48d3121124b5bb8b15a131c8521bfe?

**Comment by soliton-** [comment]
No, that is just sent on connect. That or a similar message would need to be sent also when returning to the lobby after a game.

Also I think the client side logic for filtering this message according to preferences is still missing.
