### ISSUE TITLE
Halo sprites in 2p - Aethermaw are rendered on top of fog (GNA #22544)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1406]
**[Original submission](https://gna.org/bugs/index.php?22544)** by involution on 2014-08-28

Have a look at the mainline MP map, 2p - Aethermaw. If you glance around off to the sides at the still scenes, many sprite classes including the Saurians and the Death Knight are displayed with a visual bug that did not appear in 1.10. (I think we had some more severe problems earlier in 1.11 series though that have been fixed since, not sure when this particular issue was introduced.)

(Reproduced on Linux Mint 16)
Release: 1.11.16
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-07**

**involution wrote:**

> Uploading some screenshots, since apparently not everyone gets this bug.
> 
> 
> 
> http://imgur.com/a/Zbyn4#yxAl1Td

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-07**

**shadowmaster changed title:** sprites placed as images in scenarios not being darkened correctly -> Halo sprites in 2p - Aethermaw are rendered on top of fog

**shadowmaster wrote:**

> Changed the bug summary to something a bit more specific.
> 
> 
> 
> Aethermaw uses a few halos for sprites that don't fit in the 72x72 hex mask, to work around this limitation in [item] and terrain rendering. What we could do is replace those halos with multihex terrain graphics rules so that they are overlaid by fog correctly.
> 
> 
> 
> I'll look into it later.

**shadowmaster changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-22**

**wedge009 wrote:**

> Oh, I didn't realise those units weren't supposed to be in the foreground. No wonder I was confused when I saw them.
> 
> 
> 
> Still present in 1.13.1+dev.

**Comment by Vultraz** [comment]
Assigning to myself. Not fixed on accelerated_rendering yet but I have a better chance of fixing it there.

**Comment by Vultraz** [comment]
Fixed on accelerated_rendering.

**Comment by CelticMinstrel** [comment]
Should this be reopened?

**Comment by Wedge009** [comment]
Actually re-opening (not sure why I didn't do that before).

**Comment by Wedge009** [comment]
Seems to be resolved for 1.16, but still present in master. As long as #5963 isn't forgotten, I suppose that should be fine.
