### ISSUE TITLE
wesnothd forum user handler does not support phpBB 3.1/3.2

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#1761]
The wesnothd forum user handler (both in 1.12 and master) does not support the new password hashing algorithm used by phpBB 3.1 and 3.2, and therefore fails to authenticate all users with the following error:

```
Even though your nickname is registered on this server you cannot log in due to an error in the hashing algorithm. Logging into your forum account on http://forum.wesnoth.org may fix this problem.
```

Users can still join the server but they are handled as if their account is inactive/non-existent, so they cannot claim ownership of their nickname or (in the case of server moderators) be automatically granted mod privileges.

This is a pretty serious issue as it's setting back the upgrade process for the Wesnoth.org infrastructure right now. If fixed, it needs to be fixed both on 1.12 and 1.13.x/master even if 1.14 is released first until the 1.12 server average population becomes sufficiently low for it to be a non-issue.

**Comment by GregoryLundberg** [comment]
@CelticMinstrel

**Comment by shikadilord** [comment]
Going by <https://www.phpbb.com/community/viewtopic.php?p=14357621#p14357621>, phpBB 3.1/3.2 convert salted MD5 passwords to use **bcrypt** every time a user logs in. I'm able to confirm this by comparing the `user_password` column for an account that has logged in after the upgrade (`shadowm`) and one that hasn't (`vultraz`):

```
MariaDB [weldyn2]> SELECT username,user_type,user_password FROM phpbb3_users WHERE username IN ('shadowm', 'vultraz');
+----------+-----------+--------------------------------------------------------------+
| username | user_type | user_password                                                |
+----------+-----------+--------------------------------------------------------------+
| vultraz  |         3 | $H$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                           |
| shadowm  |         3 | $2y$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
+----------+-----------+--------------------------------------------------------------+
```

**Comment by loonycyborg** [comment]
So if we update both client and server to use bcrypt users with old hashes will get a message telling them to log in to forums which actually would make sense in that case.

**Comment by pydsigner** [comment]
@loonycyborg that would also solve what is really a glaring security issue.

**Comment by gfgtdf** [comment]
I think we won't want to we don't need client updates here, just have the client send the unhashed password to the server and let the server do the hashing.


In theory it also makes much more sense to hash the passwords on the server since that way a potential hacker that somehow got a copy of the database cannot login on te server. (Unlike the current implemtation were he could easily use the password hashsh stored on the server to login and skip the clientside hashing).

The only problem here is whether we can accept that the real password (which is also the forum password) is sended uncrypted via network. Ideally this would be solved by some ssl-like protected connection.

**Comment by CelticMinstrel** [comment]
Sending unhashed passwords over the network is a security risk in itself. Any method of fixing that requires client updates. I don't think there's any way to avoid a client update here.

**Comment by loonycyborg** [comment]
I've implemented support for bcrypt in a branch for now. It was easy to support both md5 and bcrypt logins at the same time since hash prefix was sent to client as part of "salt" which is in fact part of original hash from the forum(prefix + salt) with random digits added("outer salt" as I'd call it). Client is first hashing user's password based on original forum hash's salt to recreate forum hash on the client, then it hashes it with "outer salt" and sends the result to server. The server hashes forum's hash with "outer salt" and compares it with hash sent by user. This commit changes it so it uses bcrypt to compute forum hash on the client though md5 is still used for outer hash. Not sure if it's desirable/possible to convert outer hash to bcrypt too.

**Comment by loonycyborg** [comment]
It would be nice to wrap the connection into ssl indeed, but it's not what this issue is about. This issue is strictly about supporting newer phpBB versions. Currently all passwords and sensitive hashes are never passed between client and server. Instead salted md5 hashes of them are sent. Not sure how secure this is.

**Comment by gfgtdf** [comment]
> but it's not what this issue is about

My point was that, if the connection was protected, we could make the client just send the password so that the hashing can be done complteley the server, in particular the client wouldn't need to know about the phpbb encryption method and we wouldn't get into situation like this again.

**Comment by CelticMinstrel** [comment]
I commented directly on commit 7cf96ce, in case you missed it.

**Comment by loonycyborg** [comment]
I addressed two of your concerns in following commits to that branch. I still don't see any direct support for bcrypt in openssl. Though Botan has support for it: https://botan.randombit.net/manual/passhash.html
Not sure if it's worth changing our general crypto lib just for bcrypt, and using two different general purpose crypto libs at the same time looks kinda awkward.
