### ISSUE TITLE
Sound broken, preferences auto-set to "no"

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#2443]
Apologies if this is related to something already reported, but in 1.13.11 (e260fe9543) going to Menu->Preferences results in a dialog that can only be closed by "close" button, which must be the same as "cancel", since selections in preferences are ignored and forgotten.

**Comment by doofus-01** [comment]
I've added some labels because I know we are late in the relase cycle, and if this is really an issue for others, this seems important.

**Comment by GregoryLundberg** [comment]
I cannot duplicate this. Preferences persist when I click Close and across restarting the client. I tried each section and Close saved it.

**Comment by doofus-01** [comment]
Sound preferences are the only ones that are affected.  I think the problem is not with the dialogue.  I should note that I had problems with the SDL2_mixer/image_2.0.2, and could not compile without downgrading to 2.0.1 for those two.  I'm running openSuSE Leap 42.3, new installation.  

If no one else is having trouble with audio, it is specific to my set-up, and not worth worrying about until I can narrow it down.
But merely having Preferences persist as @GregoryLundberg does not mean all is well.

**Comment by sevu** [comment]
I couldn't reproduce, but
- There was an issue that the scons tests for sdl_mixer failed after the update to 2.0.2 (solved by now)
- If wesnoth quits in an unexpected way, like a CTRL+C, preferences which have been changed are back to what they where before starting wesnoth

**Comment by Vultraz** [comment]
I cannot repro either, either with general preferences or sound-related ones.

**Comment by Wedge009** [comment]
I don't appear to have this issue either, compiled at 057a5305, in both Window and Linux. All preferences tabs appear to be okay, both after a close and after a restart.

I'm using SDL2_mixer/image 2.0.2 in Windows but only have 2.0.1 in Linux.

**Comment by doofus-01** [comment]
Preferences dialog is not the problem, at least as far as I can tell, so I'll remove th UI label.
 - I'd updated to 056fab1e37 , still doesn't work.  
 - I manually changed the "preferences" file to music=yes, but it got changed back to music=no after I started Wesnoth.  
 - I don't see any configure errors when when running scons, aside from dbus-1, fribidi, and history.  No errors on start-up.

This may be looking more tech-support than bug-report, but as far as real bugs, there should be some sort of error if something is wrong, not just a quiet setting of the preferences.

**Comment by CelticMinstrel** [comment]
I seem to recall that Wesnoth automatically turns off the sound preferences if it's unable to initialize the audio device on startup, or something like that. I assume there's a logdomain for this, do you get anything telling if you set it to info level?

**Comment by doofus-01** [comment]
That's a good idea, I should have tried it earlier, but unfortunately info level doesn't seem to give anything useful.  
1. I set my preferences file manually to sound=yes,
2.  run `./wesnoth --log-info=all &> logs-info.txt`, 
3.  click on preferences button and verify sound has been set back to no (boxes unchecked), 
4.  close wesnoth and search that txt file for "sound" and "audio"

All I find are references to the GUI elements for "sound"
All I find for "audio" is `info audio: resolved music track 'main_menu.ogg' into ... ` (part of starting) and `info audio: Audio device released.` (part of quitting)

**Comment by CelticMinstrel** [comment]
I think debug is an even lower level than info (so could have more info), but I wouldn't expect it to have anything more useful... but I guess it wouldn't hurt to try `--log-debug=audio` (since from your previous test it looks like "audio" is the relevant logdomain).

**Comment by doofus-01** [comment]
Yeah, it shows the same messages.  Nothing that would indicate trouble.

**Comment by doofus-01** [comment]
(non-programmer talking) Updating Boost (1.54-> 1.61) did nothing for this issue.  Probably is an SDL issue rather than boost, but I thought I'd just document it here in small chance it matters.

**Comment by doofus-01** [comment]
I was compiling wesnoth.  No, I no longer have the issue, though I never figured out what the issue was.  Same computer with different Linux distribution works fine.  No reason for this to remain open.  Thanks.

**Comment by Wedge009** [comment]
Thanks for confirming.
