### ISSUE TITLE
mac osx: jammed scroll/cursor messes with gameplay 1.13.14

### ISSUE THREAD

**Issue by ghype** [wesnoth/wesnoth#2971]
i am reporting this because wesnoth is unplayable when this happens in 1.13.14

the  map movement gets jammed in one direction and no matter how much i counter-scroll it will always move in that direction. it can happen in any of the 4 main directions and simple save&reload fix it temporarily until it come back after 3-4 turns.
no clue what triggers this bug.

note: this happened back then on release of 1.12 too but it was patched at some point it never occure on 1.12.

i uploaded a screenrecord on dropbox to show the bug.
https://www.dropbox.com/s/45guvj1m2r00kg8/1.13.14%20scroll%20bug.mov?dl=0

system: mac osx 10.13.12

**Comment by ghype** [comment]
gfg just mentioned that by pressing the key-arrow in the jammed direction it goes away. which is very nice since its very annoying.  but the cause of that aint fixed.

so yeah, i know now how to deal with it thanks to gfg but i think this might be a problem for everyone who uses key arrows to move around. hope this is not in 1.14.0 too

**Comment by Xel** [comment]
Can confirm this too on Archlinux in 1.14.0-1

**Comment by ProditorMagnus** [comment]
And on windows too. Easy to replicate by scrolling and pressing esc. Not limited to 4 directions, same happens with diagonal scrolling.

**Comment by Xel** [comment]
Fixed in 1.14.0-2 i believe.

**Comment by singalen** [comment]
@Xel Are you sure? I don't have the very latest 1.14, but it reproduces for me.

**Comment by Xel** [comment]
@singalen Yup. I have the latest, (Updated about an hour ago) and i haven't been able to reproduce it.

**Comment by singalen** [comment]
I'm not so sure. I checked, my sources are still recent, and it reproduces for me.

**Comment by ghype** [comment]
i can confirm the bug in 1.14.0 too.
same way reproduced by ending turn/dialog while holding any of the arrow keys

**Comment by ghype** [comment]
some more playing on 1.14.0 as it happened again after a lag.
stuck into one direction where i was scrolling before the lag.
however, no dialog nor ending turn. just scrolling a very large map.

**Comment by singalen** [comment]
Apparently, [the 11-years-old code](https://github.com/wesnoth/wesnoth/blame/2edcbdced8608936c50a9ec1e54ca07644d713d7/src/events.cpp#L436) is at fault.
Commits [one](https://github.com/wesnoth/wesnoth/commit/3f4afe669c8b33bf28591c7e73f65afa25458242) and [two](https://github.com/wesnoth/wesnoth/commit/7966589b87c84f45f7c3c8bd96f6cd4e6ebe29af) no longer exist, but this workaround is still there.
Testing...

**Comment by singalen** [comment]
@Wedge009 wat. Oh...
What system are you testing on?

**Comment by Wedge009** [comment]
Windows and Linux.

**Comment by Xel** [comment]
Strange that i can't reproduce it on the minor patched version, but rolling back to 1.14.0 definitely reproduces it

**Comment by singalen** [comment]
I can believe that it still reproduces. The hotkey system is flawed: it is not checking if key is pressed, but tracks press/release events, which it can easily miss.
@Wedge009, if you're *really* sure it reproduces on the revision you mentioned, let's leave this one open. I might have the time to revisit it once again, but no promises.

**Comment by Wedge009** [comment]
We seem to be in agreement about the issue... so why are you questioning whether I can replicate the issue or not? (Don't read that in an accusatory tone, I'm just confused...)

I recompiled 1.14 today (b8ecbaa3) and it's still there. I'm using the very simple method that @ProditorMagnus described: on a sufficiently large enough map just hold down an arrow key to starts scrolling, press escape to trigger the 'do you wan to exit' confirmation dialogue while still holding down the arrow key, release the arrow key, press escape again to dismiss the confirmation dialogue, and then observe the map continue to scroll without any input. Scrolling in the opposite direction is only possible after pressing the original arrow key again to get the game to recognise the release key event.

**Comment by CelticMinstrel** [comment]
Um, that seems a bit too specific? And `HOTKEY_SCROLL_UP_EVENT` is not an SDL event, is it?

**Comment by singalen** [comment]
We handle exactly 4 key-release events in Wesnoth, in `command_executor::do_execute_command`, the cursor keys. And they are only used to track press-release cycles, to generate repeated `HOTKEY_SCROLL_UP` etc events. That is too specific. Any other hypothetical key-up hotkeys would also be counterintuitive.

This current cursor keys handling is flawed, because (key-up) events can be lost. We even remove events ourselves. One example - events are removed if they were generated before a current window was activated - which is exactly how this bug manifests now.

The only reliable way to react to cursor keys being held is to actually check if they are held.

Yes, `HOTKEY_SCROLL_UP_EVENT` is not a SDL event. It would have to be added to `events.hpp` like `DOUBLE_CLICK_EVENT` was added.

**Comment by singalen** [comment]
That's the whole idea - introduce a "held down" event instead of "released".

**Comment by Xel** [comment]
Wasn't addressed in the new release. Is this affecting gameplay for anyone?

**Comment by singalen** [comment]
There are, in fact, two issues here:
* cursor keys could get stuck without any visible reason;
* cursor keys get stuck when a window state changes.

The committed fix addresses the first issue.

**Comment by jostephd** [comment]
I can reproduce this with latest 1.14 (1caadc2793067a771263b6b21f443a8528f00660) on Linux as follows:

1. Press the Up key
2. Press the Ctrl key
3. Release the Up key
4. Release the Ctrl key

At this point the viewport continues moving up, until it eventually becomes stuck at the top of the map.  Pressing and releasing Up unsticks it.

"Viewport is stuck against the top of the map" also happens to me in HttT S1 if I neither alt-tab nor move the mouse between starting wesnoth and dismissing the objectives dialog.  The viewport moving to the top in the first place is #2149, but back when #2149 it was possible to scroll away from the top of the map normally after the viewport moved there (i.e. it didn't get stuck).

**Comment by Wedge009** [comment]
I tried the Ctrl method above with 1.14.9 release and it's still present. Esc with exit confirmation dialogue is the same as Ctrl.

**Comment by Wedge009** [comment]
Reconfirmed with both Ctrl and Esc keys on 1.18.0.
