### ISSUE TITLE
Blurred elements in the title screen are not rendered correctly after resizing window

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#8023]
### Game and System Information

The Battle for Wesnoth version 1.17.22+dev (b8adf0cd-Clean) x86_64
Running on Freedesktop.org SDK 22.08 (Flatpak runtime) x86_64

Libraries
=========

Boost:             1.67
Lua:               5.4.6
OpenSSL/libcrypto: 3.0.0e-dev (runtime 3.0.0k-dev)
libcurl:           7.85.0 (runtime 7.86.0-DEV)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.50.9 (runtime 1.51.0)
SDL:               2.24.0 (runtime 2.24.0)
SDL_image:         2.6.2 (runtime 2.6.3)
SDL_mixer:         2.6.0 (runtime 2.6.3)

Current video settings
======================

SDL video drivers:        [x11] wayland dummy evdev
Window size:              800x540
Game canvas size:         800x540
Final render target size: 800x540
Screen refresh rate:      60
Screen dpi:               92.02x91.44
Renderer:                 opengl (hw)
Maximum texture size:     16384x16384
VSync:                    off

### Description of the bug

![image](https://github.com/wesnoth/wesnoth/assets/3605541/8f3198f6-7e79-45b4-88c7-5bf89aa536d3)

### Steps to reproduce the behavior

1. Resize the game window when on title screen the

**Comment by mesilliac** [comment]
Confirmed on my end. Probably just needs to queue a reblur at the appropriate time. I'll take a look at it later.

**Comment by mesilliac** [comment]
Should be fixed by #8026

**Comment by gfgtdf** [comment]
Does this surely only apply to tiltescreen?

**Comment by mesilliac** [comment]
I made it so the blur is always recalculated when the canvas size or location changes, so it should work anywhere.

There is an issue if the blurred thing has another thing on top of it when it recalculates (like the preferences dialog for example). Those issues can just be handled case-by-case. It's because the canvas object itself is handling the blur, whereas it should ideally be done at a higher level. But that's a lot of work to implement for very small gain, so it's a more long-term todo, for when the blur can actually be done in hardware (SDL3, probably).

**Comment by gfgtdf** [comment]
This sounds like it can in theory still happen if for example the user resized the window (by dragging the edge with the mouse) while the language or load game me is are open in titlescreen

**Comment by mesilliac** [comment]
Yes. But i'm not going to fix that.
