### ISSUE TITLE
Drop new back/forward arrow graphics

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#9940]
Previously, I remember we had nice back and forward arrow buttons. They fit well with the rest of the UI, and with the texture of the map and the wooden table/wall background.

Now, running 1.19.9, I see garish, non-button, perfect-geometrical-shape-based forward and background arrow graphics. I really dislike them and wish you could go back to what we had before.

**Comment by Wedge009** [comment]
Please clarify what you're referring to. I can only guess you mean the forward and back buttons for the story screens. I don't necessarily like them myself, but it's hardly a deal-breaker.

**Comment by Vultraz** [comment]
FWIW, when we merged them the intent was to go back and refine the graphics.

**Comment by eyalroz** [comment]
> Please clarify what you're referring to. I can only guess you mean the forward and back buttons for the story screens. 

Yes, those.

![Image](https://github.com/user-attachments/assets/94a6b67a-1c44-4a75-b881-5d00a40810eb)

> it's hardly a deal-breaker.

I won't delete Wesnoth because of it, but the question is: Previous graphics, or these graphics. These are much worse even in principle, I doubt that refinement will make that better.

**Comment by Gothyoba** [comment]
The larger buttons are easier to use and an accessiblity improvement, and they look nicer in my opinion. Refinements would he enough imo if they don’t quite fit in. Personally I find this a much more interesting design than using the same button like interface as the rest pf the UI, while still not too odd.

**Comment by eyalroz** [comment]
> The larger buttons are easier to use and an accessiblity improvement

That is a strange claim about a game with a large amount of handful-of-pixels-sized graphical elements. I don't think that is is a serious argument, and am guessing you're retroactively justifying this change.

**Comment by babaissarkar** [comment]
I think @ForestDragon-wesnoth had a custom UMC theme that allows one to use the 1.18 story screen.
That aside, I admit that those buttons look sort of different, but their intention was to give the user a much bigger click area and make the design look much less claustrophobic and symmetric and at the same time making more efficient use of the screen space we had. It also plays nicely with both touchscreen and mouse devices.

**Comment by ForestDragon-wesnoth** [comment]
> I think [@ForestDragon-wesnoth](https://github.com/ForestDragon-wesnoth) had a custom UMC theme that allows one to use the 1.18 story screen. 

The add-on is not yet released at the moment. I may potentially return to it at some point in the future.
